### PR TITLE
Update BiomesMapping.java

### PR DESCRIPTION
**Pull request by Uight**
Updated to work with Minecraft 1.13. Works great.

### CODE REVIEW

**Comment by Uight** [comment]
Just use all files i updated to make this plugin configuratable so you dont need to hard code the changes you want.

**Comment by junebug12851** [comment]
Sorry been busy at work but thank you so much for this, I'm looking through all what you did

**Comment by junebug12851** [comment]
Thank You! I look forward to testing it out myself when I get a chance

**Comment by Uight** [comment]
I hope  you cant test it the config seems to work if you change it once but if you do another change and then restart im not 100% szre what will happen.

**Comment by Uight** [comment]
I wonder if you ever had a Problem with the plugin you wrote. If i change some Basic Biomes like desert to plains it works perfectly. However there seem to be some Biomes which if replaced completly fuck up world generation. I replaced the to shore biomes by beach and no rivers where generated. And somehow im missing the hot biomes when replacing many of the cold biomes through plains and end up with a world with mostly plains.

**Pull request merged**
